title: Vinay Jain
url: https://vinayjain.me
description:
show_excerpts: false # set to true to show excerpts on the homepage


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: vinayjn7
    github:  vinayjn
    linkedin: vinayjn

header_pages:
 - about.md
 - bookshelf.md
 - uses.md

disqus:
    shortname: koderme

# Build settings
theme: minima
permalink: posts/:slug
plugins:
 - jekyll-feed
 - jekyll-seo-tag
