# Site settings
title: Vinay Jain
email: vinay.jn7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programmer | Technophile | Amateur iOS App Developer
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://vinayjn.github.io" # the base hostname & protocol for your site
twitter_username: v1n4yjn
github_username:  vinayjn
facebook_username: vinayjn
# Build settings
markdown: kramdown
excerpt_separator: vinay